package:
  format-version: "1.0.0"
  name: "core_apps_sama7d65"
  version: "v3.0.0"
  type: "application"
  status: "production"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.14.0"